kind: pipeline
type: docker
name: build images

steps:
- name: build
  image: docker:dind
  privileged: true
  commands:
   - ./build.sh
  when:
    event: push

- name: remove build
  image: docker:dind
  privileged: true
  commands:
   - ./cleanup.sh
  when:
    event: pull_request
    pull_request: closed

volumes:
- name: dockersock
  path: /var/run

