kind: pipeline
type: docker
name: build images

steps:
- name: build
  image: docker:dind
  privileged: true
  commands:
   - echo $DRONE_SOURCE_BRANCH
   - echo $DRONE_TARGET_BRANCH
   - echo $DRONE_PULL_REQUEST
   - ./build.sh

- name: remove build
  image: docker:dind
  privileged: true
  commands:
   - ./cleanup.sh
  when:
    event: pull_request
    pull_request: closed

volumes:
- name: dockersock
  path: /var/run

