kind: pipeline
type: docker
name: build images

steps:
- name: build
  image: docker:dind
  privileged: true
  commands:
   - ./build.sh
volumes:
- name: dockersock
  path: /var/run

- name: remove build
  image: docker:dind
  privileged: true
  commands:
   - ./cleanup.sh
  when:
    pull_request: closed
